[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.1.168 ; Replace with your IP

lib_deps = 
    https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git
    adafruit/Adafruit GFX Library @ ^1.11.9
    knolleary/PubSubClient @ ^2.8
    ayushsharma82/WebSerial @ ^2.0.8
    mathieucarbou/ESPAsyncWebServer @ ^3.4.5
